### ISSUE TITLE
Should be transferred under @kiwitcms

### ISSUE THREAD

**Issue by atodorov** [kiwitcms/django-plugin#1]
@brymut I think we should start by transfering this repository under the @kiwitcms organization on GitHub but you may not have permissions to do so yourself.  You can try though.

If that doesn't work then you will need to add me as an administrator to the repository so I can transfer it and adjust the permissions for the new repo for you. 

I will open a few more issues, they will be migrated automatically.

**Comment by brymut** [comment]
Github won't let me transfer ownership over to @kiwitcms, I've just invited you for direct access

**Comment by atodorov** [comment]
I don't see the Settings tab. I need to have Admin role to be able to access the transfer section.

**Comment by brymut** [comment]
I can't figure out how to assign Admin Role, I've sent a transfer ownership request to your username instead, maybe it'll be easier if you transferred it to @kiwitcms from your account
