### ISSUE TITLE
Make pylint happy (open PR)

### ISSUE THREAD

**Issue by atodorov** [kiwitcms/django-plugin#13]
@brymut now that this repository has some initial CI configuration I've updated the settings to make the master branch protected so we can't push directly into it. 

Please open pull requests for any subsequent work and I will review and merge them. 

This issue deals with making pylint happy so it doesn't report issues.

**Comment by brymut** [comment]
Sounds good, I've added a PR. Should be working okay now and can have a look at it when you can.
