### ISSUE TITLE
Don't hardcode Django version in requirements.txt

### ISSUE THREAD

**Issue by atodorov** [kiwitcms/django-plugin#2]
We would like people who use different versions of Django to be able to use this plugin. Don't hard-code a version unless you are using functionality that isn't available in older versions.

I say don't hard-code Django at all and if something fails for somebody we can deal with it when that happens.

**Comment by brymut** [comment]
Yep, makes much more sense.

**Comment by brymut** [comment]
I've updated the requirements.txt to remove the version requirement on Django

**Comment by atodorov** [comment]
> I've updated the requirements.txt to remove the version requirement on Django

FYI please use `Closes #` or `Fixes #` and the actual issue number in your commit logs  when dealing with these issues. That way GitHub will close them automatically and also leave a reference to the commit which fixed the actual issue.
