### ISSUE TITLE
DebugSQLTestResult doesn't add SQL to Kiwi TCMS

### ISSUE THREAD

**Issue by atodorov** [kiwitcms/django-plugin#20]
The current implementation of DebugSQLTestResult has been copied directly from Django and it doesn't seem to me that it does anything useful. 

There is some sense if this class is used that the printed SQL statements are added as comments to the TestExecution results in Kiwi TCMS. Otherwise they are visible only on the terminal which implies a manual debugging session (which sort of negates the integration with Kiwi TCMS in the first place).

Let's keep this issue open til the end to see how/if the TestResult class will change and if there won't be a good way to hook the SQL into it with simple overrides without copying from Django.

**Comment by brymut** [comment]
@atodorov Should the SQL be added at this point as comments or do we just do away with DebugSQLTestResult? I'm starting to see this more of a debugging tool than a useful addition for reporting to Kiwi.

**Comment by atodorov** [comment]
> @atodorov Should the SQL be added at this point as comments or do we just do away with DebugSQLTestResult? I'm starting to see this more of a debugging tool than a useful addition for reporting to Kiwi.

Because this class already exists I think it makes more sense to add the SQL statements as comments to the test execution instead of removing the entire class. It should still be fairly minimal in terms of change.

I don't have experience with this test runner and IDK whether people use it in actual testing environment (and if yes how exactly) or if they use it more as a debugging tool.
