### ISSUE TITLE
Review of statuses

### ISSUE THREAD

**Issue by atodorov** [kiwitcms/django-plugin#23]
Starting with Kiwi TCMS v8.0 TestExecution statuses can be customized and names aren't very reliable anymore. 

If searching by name fails then the implementation should fallback to searching by weight where the only 3 weights are:

0 - idle, running, not executed, etc. Status which has not been completed yet
> 0 (take the first one or the last one) - positive status generally indicating success. Because you don't know what each status means take the first or the last one and use it. In other environments users can override the default Django plugin classes and provide more integration if they wish. (see the documentation for the robotframework plugin)

< 0 - negative status generally indicating some sort of error or failure. Again take the first or the last one and leave it be.

in addError - we have a status named ERROR by default

addExpectedFailure - I think an expected failure is a PASS (a positive result) but we don't have this by default in the DB. I don't have much experience with that kinds of tests (need to experiment a bit first) but a logic way goes to try adding a new status in the DB if there is not such and use it. A safe bet is to use PASSED I think. I'll check more on this.

addUnexpectedSuccess - that should be a failing status IMO but I don't see actual integration with Kiwi TCMS for this method. Same comment as above - I have to check more on this.

**Comment by brymut** [comment]
I didn't understand the customized status before, but now I get it. Is there any way to search by weight using `tcms-api`? I may be missing something but it looks like we can only do so by name atm.

**Comment by brymut** [comment]
@atodorov Is there any more I can do about this atm?

**Comment by atodorov** [comment]
> I didn't understand the customized status before, but now I get it. Is there any way to search by weight using `tcms-api`? 

See https://kiwitcms.readthedocs.io/en/latest/modules/tcms.rpc.api.html#module-tcms.rpc.api

and query in a similar way like Django queries, e.g. `'weight__gt': 0`
