### ISSUE TITLE
Why/when do we need addSubTest

### ISSUE THREAD

**Issue by atodorov** [kiwitcms/django-plugin#24]
why/when do we need this method? I'm not sure when it gets triggered nor how to design sub-tests in Django. Can you provide some more info.

**Comment by brymut** [comment]
I personally haven't come across any subtests implementation on a Django project before, however I came across it from the [unittest library added in v3.4](https://docs.python.org/3/library/unittest.html#subtests) and how it can be useful in debugging in test cases using iterations, where they would normally fail on the first iteration with less information. 

This blog post has a novel example of how it can be useful in Django. I am yet to see a more fleshed out practical example, but I am for providing the functionality in this plugin just in case anyone who might use this as a runner does have some subtests in use.

**Comment by atodorov** [comment]
I see what you mean. This is a cool feature - very popular in automated testing in golang for example.

+1 for keeping the functionality here. I will take another look at it.
