### ISSUE TITLE
DRY: try-except when searching statuses

### ISSUE THREAD

**Issue by atodorov** [kiwitcms/django-plugin#50]
I think it would be better if searching for status + the fall back in case the status isn't found is organized more neatly into separate method(s). This will minimize code duplication and make the tools happier but will also make any override (in case somebody has their own customized statuses) a tad easier.

However thinking about it it looks like the best place for this will be in the tcms-api repository and just call appropriate methods from this plugin. @brymut what do you think ?

Note: I think this is the last bit that remains and then this plugin should be ready for a release & we can update the docs & close the issue in the main repo.

**Comment by brymut** [comment]
Yes, it does make sense and there is quite a bit of unnecessary duplication. I'll set up a PR in the tcms-api repo and will update the calls in this repo when its properly worked out there.
