### ISSUE TITLE
Extra section in README should point to official docs

### ISSUE THREAD

**Issue by atodorov** [kiwitcms/django-plugin#8]
The section which describes what variables exist to drive the plugin backend should not be listed here in the README but a reference to the official documentation. The reason is that any change upstream will affect all Python based plugins and we want to keep the documentation in a central place. For example see how https://github.com/kiwitcms/robotframework-plugin documents the bare minimum and only the RF specifics .

**Comment by brymut** [comment]
I've updated the README, I'll try to keep the document to this package's specifics from now on and add references to the official docs on any dependencies that may be useful for anyone using this.
